#!/bin/bash

BEAN7="./bean_7.0.9.exe"

PROD="local"
# PROD="prod-12"

########## MC-sig: Psi(2S)->pi+pi-J/Psi->phi eta #####################
# we need nt1 for effisiency study
function run_mcsig() {
  DAT=$1
  if [ -f PsipJpsiPhiEta/local/Lists/mcsig_${DAT}_709.list ];
  then
    printf "run mcsig_kkmc_${DAT}\n"
    ${BEAN7} \
      -u DelClonedTrks \
      -u PsipHelixParCor \
      -u PsipJpsiPhiEta \
      -L PsipJpsiPhiEta/local/Lists/mcsig_${DAT}_709.list \
      -h PsipJpsiPhiEta/$PROD/mcsig_kkmc_${DAT}.root \
      > PsipJpsiPhiEta/$PROD/mcsig_kkmc_${DAT}.out 2>&1 &
  fi

}

#  run_mcsig 09
#  run_mcsig 12
#  run_mcsig 21

########## MC-EtaEff: Psi(2S)->pi+pi-J/Psi->gamma eta ################
function run_mcgammaeta() {
  DAT=$1
  if [ -f PsipJpsiPhiEta/local/Lists/mcgammaeta2_${DAT}_709.list ];
  then
    printf "run mc gammaeta2_kkmc_${DAT}\n"
    ${BEAN7} \
      -u DelClonedTrks \
      -u PsipHelixParCor \
      -u PsipJpsiGammaEta\
      -L PsipJpsiPhiEta/local/Lists/mcgammaeta2_${DAT}_709.list \
      -h PsipJpsiPhiEta/$PROD/mcgammaeta2_kkmc_${DAT}.root \
      > PsipJpsiPhiEta/$PROD/mcgammaeta2_kkmc_${DAT}.out 2>&1 &
  fi
}

#  run_mcgammaeta 09
#  run_mcgammaeta 12
#  run_mcgammaeta 21

########## MC-EtaEff: Psi(2S)->pi+pi-J/Psi->phi eta ##################
function run_mcphieta2() {
  DAT=$1
  if [ -f PsipJpsiPhiEta/local/Lists/mcphieta2_${DAT}_709.list ];
  then
    printf "run mc phieta2_kkmc_${DAT}\n"
    ${BEAN7} \
      -u DelClonedTrks \
      -u PsipHelixParCor \
      -u PsipJpsiPhiEta \
      -e noNT1=true \
      -L PsipJpsiPhiEta/local/Lists/mcphieta2_${DAT}_709.list \
      -h PsipJpsiPhiEta/$PROD/mcphieta2_kkmc_${DAT}.root \
      > PsipJpsiPhiEta/$PROD/mcphieta2_kkmc_${DAT}.out 2>&1 &
  fi
}

#  run_mcphieta2 09
#  run_mcphieta2 12
#  run_mcphieta2 21

#################### MC INCLUSIVE PSI(2S) ##################
#  DSTDIR="/data/bes3/709/psip/21mc/dst"
if [ 1 -eq 1 ]; then
  printf "run local mcinc_21\n"
  ${BEAN7} \
    -u DelClonedTrks \
    -u PsipHelixParCor \
    -u PsipJpsiPhiEta \
    -u PsipPiPiKK \
    -u PsipJpsiGammaEta\
    -e noNT1=true \
    -h PsipJpsiPhiEta/local/mcinc_21psip.root \
    -L PsipJpsiPhiEta/local/Lists/mcincl_21_709.list \
    > PsipJpsiPhiEta/local/mcinc_21psip.out 2>&1 &
fi
    #  -e noNT1=true \
    #  -L PsipJpsiPhiEta/local/Lists/mcincl_09_709.list \

#################### TEST-DEBUG ############################
if [ 0 -eq 1 ]; then
  printf " TEST\n"
  gdb -ex=r --args \
    ${BEAN7} \
    -u DelClonedTrks \
    -u PsipHelixParCor \
    -u PsipJpsiPhiEta \
    -u PsipPiPiKK \
    -u PsipJpsiGammaEta\
    -h /dev/null \
    -L PsipJpsiPhiEta/local/Lists/mcincl_21_709.list
      #  \
    #  > >(tee test.out) 2>&1
#
    #  -N 10 \
    #  > test_2608.out 2>&1
#         -u PsipPiPiKK \
#         -u PsipJpsiPhiEta \
#         -u PsipMuMuGamma\
#         -L PsipJpsiPhiEta/local/Lists/mckketa_09psip.list \
    #  ${DSTDIR}/psip2021_stream001_run66839_file*.dst \
    #  -L PsipJpsiPhiEta/local/Lists/mcsig_12psip.list \
fi

######################## OLD, UNUSED #######################

if false
then
BEAN="./bean_6.6.4.exe"

######################## 664 MC INCLUSIVE PSI(2S) ##########
if [ 0 -eq 1 ]; then
  printf "run local mcinc_12\n"
  ${BEAN} \
    -u PsipHelixParCor \
    -u PsipJpsiPhiEta \
    -u PsipPiPiKK \
    -u PsipJpsiGammaEta\
    -L PsipJpsiPhiEta/local/Lists/mcincl_12_664.list \
    -h PsipJpsiPhiEta/local/mcinc_12psip.root \
    > PsipJpsiPhiEta/local/mcinc_12psip.out 2>&1 &
fi

######################## 664 MC BACKGROUND K+K-ETA #########
if [ 0 -eq 1 ]; then
  printf "run mckketa_kkmc_12\n"
  ${BEAN} \
    -u PsipHelixParCor \
    -u PsipJpsiPhiEta \
    -L PsipJpsiPhiEta/local/Lists/mckketa_12psip.list \
    -h PsipJpsiPhiEta/$PROD/mckketa_kkmc_12.root \
    > PsipJpsiPhiEta/$PROD/mckketa_kkmc_12.out 2>&1 &
fi

######################## 664 MC ETA EFF ####################
if [ 0 -eq 1 ]; then
  printf "run mc gammaeta_kkmc_12\n"
  ${BEAN} \
    -u PsipHelixParCor \
    -u PsipJpsiGammaEta\
    -L PsipJpsiPhiEta/local/Lists/mcgammaeta_12psip.list \
    -h PsipJpsiPhiEta/$PROD/mcgammaeta_kkmc_12.root \
    > PsipJpsiPhiEta/$PROD/mcgammaeta_kkmc_12.out 2>&1 &
fi

if [ 0 -eq 1 ]; then
  printf "run mc phieta_kkmc_12\n"
  ${BEAN} \
    -u PsipHelixParCor \
    -u PsipJpsiPhiEta \
    -L PsipJpsiPhiEta/local/Lists/mcphieta2_12psip.list \
    -h PsipJpsiPhiEta/$PROD/mcphieta2_kkmc_12.root \
    > PsipJpsiPhiEta/$PROD/mcphieta2_kkmc_12.out 2>&1 &
fi

######################## MC BACKGROUND rho eta #############
MCDIR="/data/user/nefedov/bes3/psip_jpsi_rhoeta"

if [ 0 -eq 1 ]; then
  printf "run rho-eta 2012\n"
  ${BEAN} -u PsipJpsiPhiEta \
        -h PsipJpsiPhiEta/$PROD/mcrhoeta_kkmc_12.root \
        ${MCDIR}/12psip_jpsi_rhoeta_kkmc_?.dst \
        > PsipJpsiPhiEta/$PROD/mcrhoeta_kkmc_12.out 2>&1 &
fi

######################## PHOTON EFF ########################
# save in PROD_PH
# PROD_PH="prod-6ph"
PROD_PH="local"
if [ 0 -eq 1 ]; then
  printf "run ${PROD_PH} mumu_12\n"
  ${BEAN} -u PsipMuMuGamma\
        -L PsipJpsiPhiEta/local/Lists/mumu_12.list \
        -h PsipJpsiPhiEta/${PROD_PH}/mumu_12.root \
        > PsipJpsiPhiEta/${PROD_PH}/mumu_12.out 2>&1 &
fi

if [ 0 -eq 1 ]; then
  printf "run ${PROD_PH} 3pi_12\n"
  ${BEAN} -u PsipMuMuGamma\
        -L PsipJpsiPhiEta/local/Lists/3pi_12.list \
        -h PsipJpsiPhiEta/${PROD_PH}/3pi_12.root \
        > PsipJpsiPhiEta/${PROD_PH}/3pi_12.out 2>&1 &
fi

fi
########################### END ############################
